name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *' # Runs daily at 16:00 UTC

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - id: restore-rabbitmq-server-cache
        uses: actions/cache/restore@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
        with:
          path: ${{ github.workspace }}/rabbitmq-server
          key: rmq-v3.13.7-otp-26-elixir-1.16
      - id: maybe-fail-rabbitmq-server-miss
        if: steps.restore-rabbitmq-server-cache.outputs.cache-hit != 'true'
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          script: |
            core.setFailed('could not restore cached rabbitmq-server build');
      - uses: erlef/setup-beam@e6d7c94229049569db56a7ad5a540c051a010af9 # v1.20.4
        with:
          otp-version: 26
          elixir-version: 1.16
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          path: rabbitmq-server/deps/rabbitmq_queue_migration
      - run: make -C ${{ github.workspace }}/rabbitmq-server/deps/rabbitmq_queue_migration
      - run: make -C ${{ github.workspace }}/rabbitmq-server/deps/rabbitmq_queue_migration tests
